### ISSUE TITLE
How long did you take to solve this problem?

### ISSUE THREAD

**Issue by ghost** [raskolnnikov/deep_q_learning#3]
Can you explain more about your machine conifgration whether used GPU/CPU, ram etc. How long it take you to solve this problem.

**Comment by superchthonic** [comment]
Hey there
The state space for this game is not particularly huge so the training could be performed fully on my laptop's CPU. It's an Intel i5.
What do you mean by how long?

**Comment by ghost** [comment]
Time required for model training that is one hour,10 hours,one day etc. I know that DQN requires more time to train?

**Comment by superchthonic** [comment]
I think it was close to 2 hours for the DQN to obtain acceptable accuracy levels.
